---
- hosts: "{{ test_hosts|default('all') }}"
  become: true
  become_method: sudo
  tasks:
    - include: 'tasks/main.yml'
  vars_files:
    - 'defaults/main.yml'
  handlers:
    - include: 'handlers/main.yml'

  vars:
    - amonagent_api_key: "uxIDpRApV3ULEnDUAwUNA6grHLBQs91iEiQsN8pIUao"
    - amonagent_amon_instance: "http://10.0.2.2:8002"
