---
- include: tasks/setup_redhat.yml
  when: hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'

- include: tasks/setup_debian.yml
  when: hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'

- include: tasks/install.yml

# Make sure all handlers are executed before running any subsequent roles
- meta: flush_handlers
